### ISSUE TITLE
V4: Apply hover effect to buttons and links

### ISSUE THREAD

**Issue by plutonik-a** [podlove/podlove-web-player#335]
Suggestion: 
Couldn't this hover style be applied to all buttons and links as a general rule?  

```css
<style lang="scss">
  .podlove-player--share-button {
    opacity: 0.5;

    &:hover {
      opacity: 1;
    }
  }
</style>
```

https://github.com/alexander-heimbuch/podlove-web-player/blob/eacce1793d0c81dbd0b1343ec85f65eceed6eb1e/src/components/overlays/share/ShareButton.vue#L31
